### ISSUE TITLE
keepOn option does not work

### ISSUE THREAD

**Issue by veragreen119** [gregallensworth/L.Control.BoxZoom#10]
Thanks for a great plugin.  Just letting you know the keepOn option does not work.  When set to true in the control it does not change the behaviour from default behaviour.
ctlZoomBox = L.Control.boxzoom({ position:'bottomright', keepOn:true}).addTo(map);

**Comment by gregallensworth** [comment]
Thank you for letting me know. This is now fixed in `master` and in release 1.4
