### ISSUE TITLE
Demo in HTTPS?

### ISSUE THREAD

**Issue by valerio-bozzolan** [gregallensworth/L.Control.BoxZoom#15]
Hi!

I was curious about this plugin but I noticed that the demo page does not work in HTTPS:

* https://gregallensworth.github.io/L.Control.BoxZoom/

I think we have just some resources hardcoded in http and should be an easy fix. Anyway now I cannot give more help.

Thank you so much :) Very interesting plugin! In HTTP it still works.

**Comment by gregallensworth** [comment]
Hey, thanks a lot for pointing that out. I have corrected this.

- [x] changed the Leaflet CDN to HTTPS
- [x] changed map tiles to HTTPS
- [x] changed the OSM credit to HTTPS
