### ISSUE TITLE
Zoom out by box

### ISSUE THREAD

**Issue by Dot2122** [gregallensworth/L.Control.BoxZoom#5]
Hi,
First, thanks for your plugin, it’s very useful.
But I have one question; do you think it’s possible to do a zoom out by box?
Do you have some ideas?
Thanks.

**Comment by gregallensworth** [comment]
Interesting idea. What exactly would be the intended behavior, when you
draw a box and wanted to zoom out?

Zooming in on the box, it's fairly obvious: the extent of the box is the
new desired extent.

**Comment by Dot2122** [comment]
I know it's not obvious. But yes when you draw a box you zoom out.

In this case, it's the opposite. I imagine two solutions:

1. Current zoom level is 5 and you draw a box to arrive at the zoom level 7, but in case you are in zoom out mode, you arrive at zoom level 3. It's based on the way to calculate difference between then extent current and the final extent

2. The box represents the extent you want zoom out. I don't know how for now, but maybe by a coefficient for zoom out or ratio between two extents, why not...
